variable "app" {}
variable "env" {}
variable "vpc_id" {}
variable "sng1_id" {}
variable "sng2_id" {}
variable "ec2sg_id" {}
variable "lbsg_id" {}
variable "ec2_instance_profile_name" {}
variable "s3_bucket" {}
variable "env_file" {}
variable "init_file" {}
variable "plugin_script" {}
variable "plugin_file" {}
variable "jobs_file" {}
variable "key_name" {}